<?php
/**
 * @file
 * Code for the Section - Text feature.
 */

include_once 'section_text.features.inc';


/**
* Implements hook_theme().
* This way content type uses theme file loacted in templates directory instead of default node.tpl.php file.
* Still it can be overriden by in theme directory.
*/
function section_text_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['node__section_text'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--section_text',
    'path' => drupal_get_path('module', 'section_text') . '/templates',
  );

  return $theme;
}

/**
* Implements hook_preprocess_hook().
*/
function section_text_preprocess_node(&$vars) {
  if (isset($vars['node'])) {
    $node = $vars['node'];
    if ($node->type == 'section_text') {
      $wrapper = entity_metadata_wrapper('node', $node);
      
      // Display title
      $display_title = $wrapper->field_text_display_title->value();
      $vars['display_text_title'] = $display_title;

      // Width of node
      if ($wrapper->field_text_width->value() == '1') {
        $vars['classes_array'][] = 'container';
      }
    }
  }

}