<?php
/**
 * @file
 * Code for the Section - Gallery feature.
 */

include_once 'section_gallery.features.inc';

/**
* Implements hook_theme().
* This way content type uses theme file loacted in templates directory instead of default node.tpl.php file.
* Still it can be overriden by in theme directory.
*/
function section_gallery_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['node__section_gallery'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--section_gallery',
    'path' => drupal_get_path('module', 'section_gallery') . '/templates',
  );

  return $theme;
}


/**
* Implements hook_preprocess_hook().
*/
function section_gallery_preprocess_node(&$vars) {
  if ($vars['type'] == 'section_gallery') {

  }
}