<?php
/**
 * @file
 * Code for the ExpressWeb - Featured Offers feature.
 */

include_once 'expressweb_featured_offers.features.inc';

/**
* Implements hook_theme().
* This way content type uses theme file loacted in templates directory instead of default node.tpl.php file.
* Still it can be overriden by in theme directory.
*/
function expressweb_featured_offers_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['node__featured_offers'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--featured_offers',
    'path' => drupal_get_path('module', 'expressweb_featured_offers') . '/templates',
  );

  return $theme;
}

/**
* Implements hook_preprocess_hook().
*/
function expressweb_featured_offers_preprocess_node(&$vars) {
  if ($vars['type'] == 'featured_offers') {
    //dsm($vars);
    $vars['image_path'] = image_style_url('width_720', $vars['field_images']['0']['uri']);
  }
}