<?php
/**
 * @file
 * Code for the Section - table feature.
 */

include_once 'section_table.features.inc';

/**
* Implements hook_theme().
* This way content type uses theme file loacted in templates directory instead of default node.tpl.php file.
* Still it can be overriden by in theme directory.
*/
function section_table_theme($existing, $type, $theme, $path) {
  $theme = array();

  $theme['node__table_price_list'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--table_price_list',
    'path' => drupal_get_path('module', 'section_table') . '/templates',
  );

  return $theme;
}

/**
* Implements hook_preprocess_hook().
*/
function section_table_preprocess_node(&$vars) {
  if ($vars['type'] == 'table_price_list') {
    $wrapper = entity_metadata_wrapper('node', $vars['node']);
    if ($wrapper->field_table_width->value() == '1') {
      $vars['classes_array'][] = 'container';
    }
  } 
}